def on_forever():
    basic.show_number(0)
    basic.pause(1000)
    basic.show_number(1)
    basic.pause(1000)
    basic.show_number(2)
    basic.pause(1000)
    basic.show_number(3)
    basic.pause(1000)
    basic.show_number(4)
    basic.pause(1000)
    basic.show_number(5)
basic.forever(on_forever)
